# Generated by Django 6.1.1 on 2026-09-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome Completo', max_length=50, verbose_name='Nome')),
                ('fone', models.CharField(help_text='Numero do Telefone', max_length=15, verbose_name='Fone')),
                ('email', models.EmailField(help_text='Endereço de email', max_length=100, unique=True, verbose_name='E-mail')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos', verbose_name='Foto')),
                ('funcao', models.CharField(help_text='Função na Empresa', max_length=100, verbose_name='Função')),
                ('data_admissao', models.DateField(help_text='Data de admissão', verbose_name='Admissão')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
