# Generated by Django 6.1.1 on 2026-10-01 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome do produto', max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Digite o preço do produto', max_digits=5, verbose_name='Preço')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Digite o quantidade do produto', max_digits=5, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(help_text='Nome do fornecedor', on_delete=django.db.models.deletion.PROTECT, related_name='fornecedores', to='fornecedores.fornecedor', verbose_name='Fornecedor')),
            ],
        ),
    ]
