# Generated by Django 6.1.1 on 2026-09-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do fornecedor', max_length=70, verbose_name='Nome')),
                ('cnpj', models.CharField(help_text='Cnpj do fornecedor', max_length=20, unique=True, verbose_name='Cnpj')),
                ('fone', models.CharField(help_text='Fone', max_length=20, verbose_name='Fone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
